### ISSUE TITLE
Skill issue

### ISSUE THREAD

**Issue by Mikutut** [KamilCodemate/chat-app#1]
Ziomuś masz dosłownie access key do API w swoim skrypcie na emoji publicznie dostępne XDDDDDDDDDD

**Comment by Mikutut** [comment]
![image](https://user-images.githubusercontent.com/65046942/218278807-4c4ec932-4b75-4148-97ac-2e096c75fa45.png)

**Comment by KamilCodemate** [comment]
No wiem ale  ten klucz pozwala tylko na get requesty ze stronki wiec co najwyżej możesz se emoji pobrac z nim

**Comment by KamilCodemate** [comment]
*W sumie nie tyle sama apka co emoji po prostu

**Comment by Mikutut** [comment]
> w sumie to mógłbym go walnąć do gitignore ale wtedy apka by ci nie działała zaraz po pobraniu repo

albo przechowywać takie rzeczy w .env ¯\_(ツ)_/¯

**Comment by KamilCodemate** [comment]
No ale mówię ci przecież że jak dam do .env to będziesz musiał sam se wbijać ma stronę i generować żeby ci to odpaliło. Z tym kluczem i tak nic nie zrobisz

**Comment by KamilCodemate** [comment]
> Ziomuś masz dosłownie access key do API w swoim skrypcie na emoji publicznie dostępne XDDDDDDDDDD

Tak samo w todoappce, jest .env ale dałem go jako publiczny żebyś nie musiał sobie generować nowego, a i tak przed ewentualym deploy'em umiem sobie wygenerować nowy
